{{- if .Values.rbac.create -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "soft-pod-memory-evicter.fullname" . }}
  labels:
    {{- include "soft-pod-memory-evicter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/eviction
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "soft-pod-memory-evicter.fullname" . }}
  labels:
    {{- include "soft-pod-memory-evicter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "soft-pod-memory-evicter.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "soft-pod-memory-evicter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
